exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'deploy', 'README.md']
permalink: pretty
paginate: 5
sass:
  style: compressed
markdown: rdiscount
rdiscount:
  extensions:
    - smart         # typographic substitutions with SmartyPants
    - autolink      # Convert URL in links, even if they aren't encased in <>